# Generated by Django 4.0.2 on 2022-04-13 02:05

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django_quill.fields
import taggit.managers
import wordofmouth.models


class Migration(migrations.Migration):

    replaces = [('wordofmouth', '0001_initial'), ('wordofmouth', '0002_recipe_pub_date'), ('wordofmouth', '0003_recipe_instructions'), ('wordofmouth', '0004_recipe_picture'), ('wordofmouth', '0005_alter_recipe_picture'), ('wordofmouth', '0004_alter_recipe_likes'), ('wordofmouth', '0006_merge_20220328_1404'), ('wordofmouth', '0007_auto_20220402_1455'), ('wordofmouth', '0008_recipe_author'), ('wordofmouth', '0007_alter_recipe_instructions_alter_recipe_picture'), ('wordofmouth', '0009_merge_20220404_1654'), ('wordofmouth', '0010_recipe_description'), ('wordofmouth', '0011_auto_20220407_1649'), ('wordofmouth', '0012_auto_20220407_1828'), ('wordofmouth', '0011_recipe_tags'), ('wordofmouth', '0013_merge_0011_recipe_tags_0012_auto_20220407_1828'), ('wordofmouth', '0014_recipe_favorites_remove_recipe_likes_recipe_likes_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('instructions', django_quill.fields.QuillField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='', verbose_name=wordofmouth.models.Recipe.rename_file)),
                ('author', models.CharField(default='', max_length=191)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('forked_id', models.PositiveIntegerField(default=0)),
                ('is_forked', models.PositiveIntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
