# Generated by Django 4.0.2 on 2022-04-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0001_squashed_0014_recipe_favorites_remove_recipe_likes_recipe_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
