# Generated by Django 4.0.2 on 2022-04-16 05:56

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0002_alter_recipe_author_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
