# Generated by Django 4.0.2 on 2022-03-27 20:08

from django.db import migrations, models
import wordofmouth.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0004_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.FileField(upload_to=wordofmouth.models.Recipe.rename_file),
        ),
    ]
