# Generated by Django 4.0.2 on 2022-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0004_alter_recipe_likes'),
        ('wordofmouth', '0005_alter_recipe_picture'),
    ]

    operations = [
    ]
