# Generated by Django 3.2.12 on 2022-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0007_auto_20220402_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='', max_length=191),
            preserve_default=False,
        ),
    ]
