# Generated by Django 4.1.dev20220219193601 on 2022-04-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0007_alter_recipe_instructions_alter_recipe_picture'),
        ('wordofmouth', '0008_recipe_author'),
    ]

    operations = [
    ]
