# Generated by Django 4.1.dev20220219193601 on 2022-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0009_merge_20220404_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
