# Generated by Django 3.2.12 on 2022-04-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0011_auto_20220407_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='forked_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_forked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
