# Generated by Django 4.0.2 on 2022-04-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordofmouth', '0011_recipe_tags'),
        ('wordofmouth', '0012_auto_20220407_1828'),
    ]

    operations = [
    ]
