# Generated by Django 4.0.2 on 2022-04-11 17:54

from django.conf import settings
from django.db import migrations, models
import wordofmouth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordofmouth', '0013_merge_0011_recipe_tags_0012_auto_20220407_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=wordofmouth.models.Recipe.rename_file),
        ),
    ]
